name = "proto_tmp"
type = "cli"

[platform.macos]
download-file = "proto_tmp_{version}_darwin.tar.gz"
checksum-file = "proto_tmp_{version}_darwin_checksums.txt"

[install]
checksum-url = "https://github.com/JLarky/proto_tmp/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/JLarky/proto_tmp/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/JLarky/proto_tmp" 
